###########
# site.title

title:    'Parkour_Bot'
subtitle: 'CS 175: Project in AI (in Minecraft)'


#########################
# more settings
encoding: UTF-8

markdown: kramdown

exclude:
- README.md
- LICENSE.md
